In [1]:
import numpy as np

In [2]:
a = np.array([1, 2])

In [3]:
a

array([1, 2])

In [4]:
np.linalg.norm(a)

2.23606797749979

In [11]:
import torch

In [12]:
a.ndim

1

In [13]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.linspace(1, 100, 30)

array([  1.        ,   4.4137931 ,   7.82758621,  11.24137931,
        14.65517241,  18.06896552,  21.48275862,  24.89655172,
        28.31034483,  31.72413793,  35.13793103,  38.55172414,
        41.96551724,  45.37931034,  48.79310345,  52.20689655,
        55.62068966,  59.03448276,  62.44827586,  65.86206897,
        69.27586207,  72.68965517,  76.10344828,  79.51724138,
        82.93103448,  86.34482759,  89.75862069,  93.17241379,
        96.5862069 , 100.        ])

In [18]:
b = np.random.randint(low=0, high=101, size=(3, 5, 10, 14))

In [19]:
b.shape

(3, 5, 10, 14)

In [20]:
b.sum()

105564

In [21]:
c = np.random.randn(5, 2, 7)

In [22]:
c

array([[[ 0.43636547, -1.60934075, -0.96924821, -0.26376328,
          0.19472653,  0.85504892, -2.1349217 ],
        [-0.51405886, -0.50026647, -0.12262804, -1.27477415,
          0.43283706,  0.9950067 , -0.12311653]],

       [[ 0.71765436,  0.92858262, -0.69688274,  0.11651103,
          1.13057288,  2.2403278 ,  1.39544504],
        [ 1.10903105, -0.22300495, -1.82780505,  0.538759  ,
          0.11195533, -0.79044269, -0.86418939]],

       [[ 0.99475629, -0.48440634,  1.17070041, -1.28598851,
         -0.57516044, -0.27992776,  0.92415818],
        [-0.04693264, -0.33386843, -0.45383683, -0.96337836,
          1.09948025,  0.11395261,  1.60160674]],

       [[ 0.34150551, -2.0931874 , -2.45661384,  2.14171828,
          0.2562172 , -0.38235304,  0.39124606],
        [ 0.87615986,  0.19575981,  0.34621349,  0.50534196,
         -0.12313307, -1.41296715,  0.76659046]],

       [[ 0.48506115,  0.54091789,  0.69883128,  0.87989475,
          0.35313421,  1.57504819,  0.5095386 ],
  

In [23]:
d = np.random.randint(low=0, high=101, size=(2, 3))

In [24]:
d

array([[89, 24,  8],
       [32, 40, 54]])

In [25]:
d.sum()

247

In [27]:
d.sum(axis=1)

array([121, 126])

In [28]:
d.mean()

41.166666666666664

In [31]:
d.mean(axis=0)
d.mean(axis=1)

array([40.33333333, 42.        ])

In [32]:
imgs = np.random.randn(12, 3, 512, 256)

In [33]:
imgs.shape

(12, 3, 512, 256)

In [34]:
imgs.mean()

0.00018709599530598357

In [36]:
half_imgs = imgs[:,:,:256,:]

In [37]:
half_imgs.shape

(12, 3, 256, 256)