In [1]:
import numpy as np

In [2]:
a = np.array([1, 2])

In [3]:
b = np.array([3, 4])

In [4]:
a_dot_b = a * b

In [5]:
a_dot_b

array([3, 8])

In [6]:
a @ b

11

In [7]:
cosine_similarity =  a @ b / np.linalg.norm(a) / np.linalg.norm(b)

In [8]:
cosine_similarity

0.9838699100999074

In [9]:
a = np.random.randn(3, 2)

In [10]:
b = np.random.randn(2)

In [12]:
print(a)
print(b)

[[ 0.11248387 -0.45992023]
 [-3.02457319  0.17972543]
 [ 1.46348641  0.80359225]]
[-0.60253388 -0.07398398]


In [13]:
a * b

array([[-0.06777534,  0.03402673],
       [ 1.82240783, -0.0132968 ],
       [-0.88180015, -0.05945295]])

In [17]:
b = np.random.randn(2, 2)

In [18]:
b

array([[ 1.9294926 , -0.80379436],
       [-1.41421465,  0.15754864]])

In [19]:
a * b

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [20]:
b = np.random.randn(1, 4)

In [21]:
b

array([[ 0.19326452, -1.65721085,  1.69751341, -0.922119  ]])

In [22]:
a * b

ValueError: operands could not be broadcast together with shapes (3,2) (1,4) 

In [23]:
b = np.random.randn(1, 2)

In [25]:
b

array([[-0.9329974 , -1.02269226]])

In [24]:
a * b

array([[-0.10494716,  0.47035686],
       [ 2.82191891, -0.18380381],
       [-1.36542901, -0.82182758]])

In [26]:
a = np.random.randn(4, 2)

In [27]:
b = np.random.randn(2, 2)

In [28]:
a

array([[2.15395719, 1.71702042],
       [1.55824903, 0.33948303],
       [1.44114557, 1.1025007 ],
       [0.93982634, 1.01041027]])

In [29]:
b

array([[-1.07182151, -2.12063692],
       [ 1.00602484, -0.45334822]])

In [30]:
a * b

ValueError: operands could not be broadcast together with shapes (4,2) (2,2) 

In [31]:
a - b

ValueError: operands could not be broadcast together with shapes (4,2) (2,2) 